version: "3.8"

services:
 app:
  container_name: "vuejs-app"
  build:
   dockerfile: "Dockerfile"
   context: "./.docker/node/"
  hostname: "vuejs-app"
  tty: true
  working_dir: "/app"
  volumes:
   - "./:/app"
  ports:
   - "3000:3000"
  environment:
   - CHOKIDAR_USEPOLLING=true
